// <auto-generated />
using System;
using Konqvist.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Konqvist.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KonqvistDbContext))]
    [Migration("20260310201148_2_6_MapOutlineGeoJson")]
    partial class _2_6_MapOutlineGeoJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.DistrictOwnershipSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistrictSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerTeamSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SnapshotTaken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DistrictSessionId");

                    b.HasIndex("OwnerTeamSessionId");

                    b.HasIndex("RoundSessionId", "DistrictSessionId", "Phase")
                        .IsUnique();

                    b.ToTable("DistrictOwnershipSnapshots", (string)null);
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.DistrictSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentOwnerTeamSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistrictTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClaimedThisRound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastClaimedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentOwnerTeamSessionId");

                    b.HasIndex("DistrictTemplateId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("DistrictSessions", (string)null);
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.GameEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActorPlayerSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoundSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorPlayerSessionId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("RoundSessionId");

                    b.ToTable("GameEvents", (string)null);
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("WaitingForPlayers");

                    b.Property<int?>("CurrentRoundSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRoundSessionId");

                    b.HasIndex("GameTemplateId");

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.PlayerSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLoggedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LocationLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("LocationLng")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LocationUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerTemplateId");

                    b.ToTable("PlayerSessions", (string)null);
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.RoundSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Gathering");

                    b.Property<bool>("VotingEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("VotingStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WinnerTeamSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("RoundTemplateId");

                    b.HasIndex("WinnerTeamSessionId");

                    b.ToTable("RoundSessions", (string)null);
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.RoundSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Oil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SnapshotTaken")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Voters")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamSessionId");

                    b.HasIndex("RoundSessionId", "TeamSessionId", "Phase")
                        .IsUnique();

                    b.ToTable("RoundSnapshots", (string)null);
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.TeamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalLikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalOil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalVoters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("TeamTemplateId");

                    b.ToTable("TeamSessions", (string)null);
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CastAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutocast")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("RoundSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetTeamSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoteValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VotingTeamSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TargetTeamSessionId");

                    b.HasIndex("VotingTeamSessionId");

                    b.HasIndex("RoundSessionId", "VotingTeamSessionId")
                        .IsUnique();

                    b.ToTable("Votes", (string)null);
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.DistrictTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Oil")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TriggerLat")
                        .HasColumnType("REAL");

                    b.Property<double>("TriggerLng")
                        .HasColumnType("REAL");

                    b.Property<double?>("TriggerRadiusMeters")
                        .HasColumnType("REAL");

                    b.Property<int>("Voters")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameTemplateId");

                    b.ToTable("DistrictTemplates", (string)null);
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.GameTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DistrictCaptureRadiusMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(50.0);

                    b.Property<string>("DistrictImportSourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("GmLoginToken")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationUpdateIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(30);

                    b.Property<string>("MapOutlineGeoJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinLocationUpdateIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PredictionBonusPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(150);

                    b.Property<int>("TotalRounds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(4);

                    b.Property<int>("VoteTimeoutPenalty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VotingDurationSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(30);

                    b.HasKey("Id");

                    b.ToTable("GameTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistrictCaptureRadiusMeters = 50.0,
                            GmLoginToken = "GM57t7",
                            LocationUpdateIntervalSeconds = 30,
                            MinLocationUpdateIntervalSeconds = 5,
                            Name = "Demo Game",
                            PredictionBonusPoints = 150,
                            TotalRounds = 2,
                            VoteTimeoutPenalty = 50,
                            VotingDurationSeconds = 30
                        });
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.PlayerTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginToken")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoginToken")
                        .IsUnique();

                    b.HasIndex("TeamTemplateId");

                    b.ToTable("PlayerTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LoginToken = "AR15ee",
                            Role = "Runner",
                            TeamTemplateId = 1
                        },
                        new
                        {
                            Id = 2,
                            LoginToken = "ATC5y85",
                            Role = "TeamLeader",
                            TeamTemplateId = 1
                        },
                        new
                        {
                            Id = 3,
                            LoginToken = "BR2q9L",
                            Role = "Runner",
                            TeamTemplateId = 2
                        },
                        new
                        {
                            Id = 4,
                            LoginToken = "BTC8k1M",
                            Role = "TeamLeader",
                            TeamTemplateId = 2
                        });
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.RoundTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoiResource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stake")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameTemplateId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("RoundTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameTemplateId = 1,
                            RoiResource = "Gold",
                            RoundNumber = 1,
                            Stake = "Gold grant doubles for the winning team this round."
                        },
                        new
                        {
                            Id = 2,
                            GameTemplateId = 1,
                            RoiResource = "Voters",
                            RoundNumber = 2,
                            Stake = "Winning team gains a voter momentum bonus."
                        });
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.TeamTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("GameTemplateId", "Name")
                        .IsUnique();

                    b.ToTable("TeamTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#1E88E5",
                            GameTemplateId = 1,
                            Name = "Alpha"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#E53935",
                            GameTemplateId = 1,
                            Name = "Bravo"
                        });
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.DistrictOwnershipSnapshot", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Session.DistrictSession", "DistrictSession")
                        .WithMany("OwnershipSnapshots")
                        .HasForeignKey("DistrictSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konqvist.Infrastructure.Entities.Session.TeamSession", "OwnerTeamSession")
                        .WithMany("OwnershipSnapshotsAsOwner")
                        .HasForeignKey("OwnerTeamSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Konqvist.Infrastructure.Entities.Session.RoundSession", "RoundSession")
                        .WithMany("OwnershipSnapshots")
                        .HasForeignKey("RoundSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistrictSession");

                    b.Navigation("OwnerTeamSession");

                    b.Navigation("RoundSession");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.DistrictSession", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Session.TeamSession", "CurrentOwnerTeamSession")
                        .WithMany("OwnedDistricts")
                        .HasForeignKey("CurrentOwnerTeamSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Konqvist.Infrastructure.Entities.Template.DistrictTemplate", "DistrictTemplate")
                        .WithMany("DistrictSessions")
                        .HasForeignKey("DistrictTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Konqvist.Infrastructure.Entities.Session.GameSession", "GameSession")
                        .WithMany("Districts")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentOwnerTeamSession");

                    b.Navigation("DistrictTemplate");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.GameEvent", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Session.PlayerSession", "ActorPlayerSession")
                        .WithMany("ActorEvents")
                        .HasForeignKey("ActorPlayerSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Konqvist.Infrastructure.Entities.Session.GameSession", "GameSession")
                        .WithMany("Events")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konqvist.Infrastructure.Entities.Session.RoundSession", "RoundSession")
                        .WithMany("Events")
                        .HasForeignKey("RoundSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ActorPlayerSession");

                    b.Navigation("GameSession");

                    b.Navigation("RoundSession");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.GameSession", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Session.RoundSession", "CurrentRoundSession")
                        .WithMany()
                        .HasForeignKey("CurrentRoundSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Konqvist.Infrastructure.Entities.Template.GameTemplate", "GameTemplate")
                        .WithMany("GameSessions")
                        .HasForeignKey("GameTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentRoundSession");

                    b.Navigation("GameTemplate");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.PlayerSession", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Session.GameSession", "GameSession")
                        .WithMany("Players")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konqvist.Infrastructure.Entities.Template.PlayerTemplate", "PlayerTemplate")
                        .WithMany("PlayerSessions")
                        .HasForeignKey("PlayerTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("PlayerTemplate");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.RoundSession", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Session.GameSession", "GameSession")
                        .WithMany("Rounds")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konqvist.Infrastructure.Entities.Template.RoundTemplate", "RoundTemplate")
                        .WithMany("RoundSessions")
                        .HasForeignKey("RoundTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Konqvist.Infrastructure.Entities.Session.TeamSession", "WinnerTeamSession")
                        .WithMany("WonRounds")
                        .HasForeignKey("WinnerTeamSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GameSession");

                    b.Navigation("RoundTemplate");

                    b.Navigation("WinnerTeamSession");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.RoundSnapshot", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Session.RoundSession", "RoundSession")
                        .WithMany("Snapshots")
                        .HasForeignKey("RoundSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konqvist.Infrastructure.Entities.Session.TeamSession", "TeamSession")
                        .WithMany("Snapshots")
                        .HasForeignKey("TeamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoundSession");

                    b.Navigation("TeamSession");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.TeamSession", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Session.GameSession", "GameSession")
                        .WithMany("Teams")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konqvist.Infrastructure.Entities.Template.TeamTemplate", "TeamTemplate")
                        .WithMany("TeamSessions")
                        .HasForeignKey("TeamTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("TeamTemplate");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.Vote", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Session.RoundSession", "RoundSession")
                        .WithMany("Votes")
                        .HasForeignKey("RoundSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konqvist.Infrastructure.Entities.Session.TeamSession", "TargetTeamSession")
                        .WithMany("VotesTargeted")
                        .HasForeignKey("TargetTeamSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Konqvist.Infrastructure.Entities.Session.TeamSession", "VotingTeamSession")
                        .WithMany("VotesCast")
                        .HasForeignKey("VotingTeamSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoundSession");

                    b.Navigation("TargetTeamSession");

                    b.Navigation("VotingTeamSession");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.DistrictTemplate", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Template.GameTemplate", "GameTemplate")
                        .WithMany("Districts")
                        .HasForeignKey("GameTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTemplate");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.PlayerTemplate", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Template.TeamTemplate", "TeamTemplate")
                        .WithMany("Players")
                        .HasForeignKey("TeamTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamTemplate");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.RoundTemplate", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Template.GameTemplate", "GameTemplate")
                        .WithMany("Rounds")
                        .HasForeignKey("GameTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTemplate");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.TeamTemplate", b =>
                {
                    b.HasOne("Konqvist.Infrastructure.Entities.Template.GameTemplate", "GameTemplate")
                        .WithMany("Teams")
                        .HasForeignKey("GameTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTemplate");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.DistrictSession", b =>
                {
                    b.Navigation("OwnershipSnapshots");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.GameSession", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("Events");

                    b.Navigation("Players");

                    b.Navigation("Rounds");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.PlayerSession", b =>
                {
                    b.Navigation("ActorEvents");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.RoundSession", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("OwnershipSnapshots");

                    b.Navigation("Snapshots");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Session.TeamSession", b =>
                {
                    b.Navigation("OwnedDistricts");

                    b.Navigation("OwnershipSnapshotsAsOwner");

                    b.Navigation("Snapshots");

                    b.Navigation("VotesCast");

                    b.Navigation("VotesTargeted");

                    b.Navigation("WonRounds");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.DistrictTemplate", b =>
                {
                    b.Navigation("DistrictSessions");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.GameTemplate", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("GameSessions");

                    b.Navigation("Rounds");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.PlayerTemplate", b =>
                {
                    b.Navigation("PlayerSessions");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.RoundTemplate", b =>
                {
                    b.Navigation("RoundSessions");
                });

            modelBuilder.Entity("Konqvist.Infrastructure.Entities.Template.TeamTemplate", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("TeamSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
