// <auto-generated />
using System;
using Konqvist.Data.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Konqvist.Data.Infrastructure.Migrations
{
    [DbContext(typeof(GameplayStateDbContext))]
    [Migration("20250101000000_InitialCreateGameplayStates")]
    partial class InitialCreateGameplayStates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Konqvist.Data.Infrastructure.GameplayStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GameDefinitionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slot", "GameDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_GameplayStates_Slot_GameDefinitionId");

                    b.ToTable("GameplayStates", t =>
                        t.HasCheckConstraint("CK_GameplayStates_Payload_IsJson", "ISJSON([Payload]) = 1"));
                });
#pragma warning restore 612, 618
        }
    }
}
